FROM maven:3.9.6-eclipse-temurin-21-jammy AS build
COPY src /app/src  
COPY pom.xml /app/
RUN mvn -f /app/pom.xml clean package
RUN cp /app/target/*with-dependencies.jar /app/algo.jar
CMD ["java","-cp", "/app/algo.jar", "at.fhhagenberg.sqelevator.Algorithm.AlgoMqttClient"]